"""Tests for the overview (grid) thumbnail endpoint /preprocessing/preview-thumb."""

from io import BytesIO

import pytest
from fastapi.testclient import TestClient
from PIL import Image

import api.services.preprocessing_cache as pc
from api.server import app


@pytest.fixture
def client(tmp_path, monkeypatch):
    """A client whose preprocessing cache lives under tmp_path (no real ~/.cache)."""
    # Point the cache at a temp dir and force a fresh singleton.
    monkeypatch.setattr(pc.PreprocessingCache, "DEFAULT_CACHE_DIR", tmp_path / "cache")
    pc.reset_cache()
    yield TestClient(app)
    pc.reset_cache()


def _make_jpeg(path, size=(1200, 800), color=(120, 60, 30)):
    Image.new("RGB", size, color).save(path, format="JPEG", quality=90)


def test_downscales_jpeg_within_size(client, tmp_path):
    img = tmp_path / "photo.jpg"
    _make_jpeg(img)

    resp = client.get("/api/v1/preprocessing/preview-thumb", params={"path": str(img), "size": 256})

    assert resp.status_code == 200
    assert resp.headers["content-type"] == "image/jpeg"
    assert resp.headers["X-Cache"] == "MISS"
    out = Image.open(BytesIO(resp.content))
    assert out.format == "JPEG"
    assert max(out.size) <= 256


def test_second_request_is_cache_hit(client, tmp_path):
    img = tmp_path / "photo.jpg"
    _make_jpeg(img)

    first = client.get(
        "/api/v1/preprocessing/preview-thumb", params={"path": str(img), "size": 256}
    )
    second = client.get(
        "/api/v1/preprocessing/preview-thumb", params={"path": str(img), "size": 256}
    )

    assert first.headers["X-Cache"] == "MISS"
    assert second.headers["X-Cache"] == "HIT"
    assert second.content == first.content


def test_honours_exif_orientation(client, tmp_path):
    # A landscape image tagged as rotated 90° (orientation 6) should come back
    # portrait after exif_transpose.
    img = tmp_path / "rot.jpg"
    exif = Image.Exif()
    exif[0x0112] = 6  # Orientation: rotate 90° CW
    Image.new("RGB", (400, 200), (10, 120, 200)).save(img, format="JPEG", exif=exif)

    resp = client.get("/api/v1/preprocessing/preview-thumb", params={"path": str(img), "size": 256})

    assert resp.status_code == 200
    out = Image.open(BytesIO(resp.content))
    # 400x200 rotated becomes portrait (height > width).
    assert out.height > out.width


def test_missing_file_returns_404(client, tmp_path):
    resp = client.get(
        "/api/v1/preprocessing/preview-thumb",
        params={"path": str(tmp_path / "nope.jpg"), "size": 256},
    )
    assert resp.status_code == 404


def test_directory_returns_400(client, tmp_path):
    resp = client.get(
        "/api/v1/preprocessing/preview-thumb",
        params={"path": str(tmp_path), "size": 256},
    )
    assert resp.status_code == 400


def test_tiny_cache_still_serves_valid_jpeg(client, tmp_path):
    # With a zero-size cache, store_grid_thumb's LRU eviction removes the file
    # immediately — the endpoint must still return the generated bytes, not 500.
    from api.services.preprocessing_cache import get_cache

    get_cache().set_max_size(0)

    img = tmp_path / "photo.jpg"
    _make_jpeg(img)

    first = client.get(
        "/api/v1/preprocessing/preview-thumb", params={"path": str(img), "size": 256}
    )
    second = client.get(
        "/api/v1/preprocessing/preview-thumb", params={"path": str(img), "size": 256}
    )

    assert first.status_code == 200
    assert second.status_code == 200
    assert Image.open(BytesIO(first.content)).format == "JPEG"
    # Nothing survives in the zero-size cache, so every request is a MISS.
    assert first.headers["X-Cache"] == "MISS"
    assert second.headers["X-Cache"] == "MISS"


def test_different_size_is_separate_cache_entry(client, tmp_path):
    img = tmp_path / "photo.jpg"
    _make_jpeg(img)

    r256 = client.get("/api/v1/preprocessing/preview-thumb", params={"path": str(img), "size": 256})
    r128 = client.get("/api/v1/preprocessing/preview-thumb", params={"path": str(img), "size": 128})

    assert r256.headers["X-Cache"] == "MISS"
    assert r128.headers["X-Cache"] == "MISS"  # size is part of the key
    assert max(Image.open(BytesIO(r128.content)).size) <= 128
